
pipeline {
    agent any
    tools {
        maven 'maven_3.6.3'
    }
    options { 
        buildDiscarder(logRotator(numToKeepStr: '3')) 
    }
    stages {
        stage ('Initialization') {
            steps {
                echo 'Initialization'
            }
        }
        stage ('Build') {
            steps {
                sh "mvn clean install"
            }
        }
    }
}