
pipeline {
    agent any
    tools {
        maven 'maven_3.6.3'
    }
    stages {
        stage ('Initialization') {
            steps {
                echo 'Initialization'
            }
        }
        stage ('Build') {
            steps {
                mvn clean install
            }
        }
    }
}